# Generated by Django 3.2 on 2022-08-22 15:39

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20220822_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_of_visit',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
