# Generated by Django 3.2 on 2022-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_appointment_date_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='day',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status_reservation',
            field=models.CharField(choices=[('cancel', 'cancel'), ('reserve', 'reserve'), ('reserved', 'reserved'), ('free', 'free')], default='free', max_length=27),
        ),
    ]
