# Generated by Django 3.2 on 2022-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor_or_patient',
            field=models.CharField(blank=True, choices=[('doctor', 'doctor'), ('patient', 'patient')], max_length=10, null=True),
        ),
    ]
