# Generated by Django 3.2 on 2022-09-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20220923_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
