# Generated by Django 3.2 on 2022-09-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_alter_patient_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=80, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
