# Generated by Django 3.2 on 2022-09-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
