# Generated by Django 3.2 on 2022-09-27 00:22

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_auto_20220925_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.PositiveBigIntegerField(null=True, validators=[patients.validators.national_code_validator]),
        ),
    ]
