# Generated by Django 3.2 on 2022-09-27 00:49

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alter_patient_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_code',
            field=models.CharField(max_length=10, null=True, validators=[patients.validators.national_code_validator]),
        ),
    ]
