# Generated by Django 3.2 on 2022-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_appointment_payment_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Insurance',
            field=models.CharField(choices=[('اتیه سازان', 'atiye sazan'), ('تامین اجتماعی', 'tamin ejtemayi'), ('سامان', 'saman'), ('دانا', 'dana'), ('ایران', 'iran'), ('هیچ کدام', 'none')], max_length=35),
        ),
    ]
