# Generated by Django 3.2 on 2022-08-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_commentfordoctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='doctor_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctorspecialist'),
        ),
    ]
