# Generated by Django 3.2 on 2022-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctoruser_doctor_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='shift',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.DoctorShift'),
        ),
    ]
