# Generated by Django 3.2 on 2022-08-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_weekdays_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='shift',
        ),
    ]
