# Generated by Django 3.2 on 2022-08-30 16:53

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_weekdays_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='registeration_date',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True),
        ),
    ]
