# Generated by Django 3.2 on 2022-09-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_doctoruser_registeration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoraddress',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='doctoraddress',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
