# Generated by Django 3.2 on 2022-09-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20220904_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='national_code',
            field=models.PositiveBigIntegerField(default=32545),
            preserve_default=False,
        ),
    ]
