# Generated by Django 3.2 on 2022-09-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_doctoruser_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='national_code',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
