# Generated by Django 3.2 on 2022-09-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctoruser_national_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='full_name',
        ),
    ]
