# Generated by Django 3.2 on 2022-09-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_remove_doctoruser_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoruser',
            old_name='cost_visit',
            new_name='cost_of_visit',
        ),
    ]
